# please create a new token github.com/settings/tokens/new .
# give repo read write and workflow permissions to the token and store its value
# add the token as a repo secret with key GH_TOKEN_1 and value equal to token value stored above

name: Update Readme ascii graph and workflow
on:
  push:
    branches: main
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: "0 */8 * * *"
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.GH_TOKEN_1 }}
        name: Using Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
        name: Install dependencies
      - run: npm install asciichart
        name: Create Chart
      - run: |
          node codes/rating_chart.js > chart.txt
          CHART=$(cat chart.txt)
          echo "::set-output name=chart::$CHART"
      - id: changed
        run: git diff --exit-code
        continue-on-error: true
        name: Commit changes
      - if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Jefferson Pereira
          author_email: jefersonpereira1331@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}