name: Update Readme ascii graph and workflow
on:
  push:
    branches: main
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
    - cron: '30 8, * * *'
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        name: Using Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
        name: Install dependencies
      - run: npm install asciichart
        name: Create Chart
      - run: |
          node codes/rating-chart.js > chart.txt
          CHART=$(cat chart.txt)
          echo "::set-output name=chart::$CHART"
      - run: cat chart.txt >> README.md
      - id: changed
        run: git diff --exit-code
        continue-on-error: true
        name: Commit changes
      - if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Jefferson Pereira
          author_email: jefersonpereira1331@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
